### ISSUE TITLE
Fix quality

### ISSUE THREAD

**Issue by fperucic** [wadda/gps3#10]
Hi,

this library looks grat. However I can't find "Fix Quality" data from the [GGA sentence](http://www.gpsinformation.org/dale/nmea.htm#GGA). Am I missing something?

Many thanks!

**Comment by wadda** [comment]
I have only wild speculation why you "can't find "Fix Quality" data from the [GGA sentence]"...quite possibly all wrong.

However, in the JSON datastream is the 'TPV' class It has a key 'mode' (self.TPV['mode'])

It is a numeric value that is always present in that 'class' JSON object	[NMEA mode: %d, 0=no mode value yet seen, 1=no fix, 2=2D, 3=3D.](http://www.catb.org/gpsd/gpsd_json.html)

That may be suitable.

**Comment by fperucic** [comment]
Yes, I saw that property on the TPV class, however I was confused with the `status` property from the older [gps.py](https://github.com/ukyg9e5r6k7gubiekd6/gpsd/blob/master/gps/gps.py#L106) which is never updated once it is set as `STATUS_NO_FIX`. Nevermind, I only thought you had something simmilar. I will kepp using the `mode` property.
