### ISSUE TITLE
TypeError: argument must be an int, or have a fileno() method.

### ISSUE THREAD

**Issue by Delgan** [wadda/gps3#12]
I try to close an AGPS3mechanism instance but it raises an error.

```python
from gps3.agps3threaded import AGPS3mechanism

gps = AGPS3mechanism()
gps.stream_data()
gps.run_thread()

print(gps.data_stream.time)

gps.stop()
```

It raises:

```python
Traceback (most recent call last):
  File "/opt/python3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/opt/python3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/python3.5/lib/python3.5/site-packages/gps3/agps3threaded.py", line 43, in unpack_data
    for new_data in self.socket:
  File "/opt/python3.5/lib/python3.5/site-packages/gps3/agps3.py", line 115, in next
    waitin, _waitout, _waiterror = select.select((self.streamSock,), (), (), timeout)
TypeError: argument must be an int, or have a fileno() method.
```
How to fix this, please?

**Comment by wadda** [comment]
A solution is to 'turn off' the data stream.  The 'stop' function now tell gpsd to 'turn off' the data stream.  

Line #59 has been changed to `self.stream_data(enable=False) ` gpsd and Python clean up the leftovers.

**Comment by wadda** [comment]
A solution is to 'turn off' the data stream.  The 'stop' function now tell gpsd to 'turn off' the data stream.  

Line #59 has been changed to `self.stream_data(enable=False) ` gpsd and Python clean up the leftovers.

Changes to the Pypi wheel will be coming.
