### ISSUE TITLE
README cleanup

### ISSUE THREAD

**Issue by dvzrv** [wadda/gps3#4]
Your README needs some serious cleanup I think.

Can you provide the code snippets as ready-to-copy snippets?
That would be very helpful!
Proper placing of comments (above lines) would also be good there.

Also: One README is enough! ;-)

**Comment by wadda** [comment]
Which README needs the cleanup?;-)  

There are two natural dithering, just as there are two sets of clients.  

README.md predates everything and had drips, draps, and images added as the project went along.

The README.rst was created to go with the entire Pypi package, specifically without the baggage of the images.  It was recently added to Github for use as a quick and dirty rst text renderer.  

Sloppiness aside, the plan is to meld them together as the dithering subsides.  The README.rst for the Pypi package likely to remain text only.  

Code snippets are a good idea.  I particularly like any cut'n'paste snippets.  I like to do that with other people code to quickly ascertain, 

1.  Does it work?

2. Is it suitable for purpose?

3. If it's 'no', or 'not enough', is either possible within my time/ability/desire constraints.  This frequently decided on the clarity of the code snippet 

I thought I was providing a ready to copy code snippet with 

    `>>> from gps3 import gps3
         gps_socket = gps3.GPSDSocket()
         gps_fix = gps3.Fix()
         gps_socket.connect()
         gps_socket.watch()
         for new_data in gps_socket:
             if new_data:
                 gps_fix.refresh(new_data)
                 print('Altitude = ',gps_fix.TPV['alt'])
                 print('Latitude = ',gps_fix.TPV['lat'])`

In retrospect, to make it more apparent I could add

    `>>> from gps3 import gps3
         gps_socket = gps3.GPSDSocket()
         gps_fix = gps3.Fix()
         gps_socket.connect(host='127.0.0.1', port=2947)
         gps_socket.watch()
         for new_data in gps_socket:
             if new_data:
                 gps_fix.refresh(new_data)
                 print('Altitude = ',gps_fix.TPV['alt'])
                 print('Latitude = ',gps_fix.TPV['lat'])`

To make it obvious where to connect to host/port if you want to modify host/port, but you lose the 'default' sense in the snippet.

But, yeah, it a good idea, I still struggle with formatting.  I just don't know how else to show you can have data spit back by the 9th line.

The curses terminals and kml file creators are basic enough, repeat the above pattern, and  (I hope) discrete enough to be cannibalised and parts reused.

But, I'll see what I can do.

**Comment by dvzrv** [comment]
I was referring to the one that is shown, when opening the repository page (so README.md).
There the code snippets are kind of broken and also not concise (sometimes gps_socket, sometimes gps_connection).
You should exchange them! ;-)

As this is a work in progress, the README.rst is much more helpful to someone, who wants to understand and use this.
The output of the terminal functionality you could btw also just put into a code block!

In any case great job so far!

**Comment by wadda** [comment]
I have no excuse, dyslexia, drugs, or just the ability to make changes on a whim and gloss over inconsistencies.  

Thanks.
