### ISSUE TITLE
Adding version tags for releases

### ISSUE THREAD

**Issue by dvzrv** [wadda/gps3#5]
The pypi version is much ahead of your github version of the code.
Can you use the tags here to get ready for pypi releases?

I'm planning to provide a package for this in Arch Linux AUR.
I'd prefer a "release version" of this code instead of a "git version" there.
Also: Using setuptools for that would be very awesome!
https://github.com/pypa/setuptools

**Comment by wadda** [comment]
The[ current Pypi version](https://pypi.python.org/pypi/gps3/0.30.3) lags the Github in trivial typos fixes and the value change and move of the `sleep(.3)` during the iteration of the socket.

The previous location would hammer the socket with 'it is here, yet?' between a sleep designed to keep it from hammering the entire time.

The current locations will sleep 0.3 - 0.1seconds between empty sockets.  Specific time is trivial. There is less granularity in cpu load for this location than the old, i.e., ranging 0.1-1.0 has less effect on load range than 0.1-1.0 did for the old, but offers faster response for this less cpu load.

The Pypi package has not been update with these incremental, or typographical fixes to consolidate them and forestall the 'version inflation'  from a trail of build numbers, as Pypi won't update with incrementing.  They mostly effect the examples.

That being said, they should be synced, or harnessed more closely. 

If you want `setup.py|cfg`,  the `MANIFEST.in` etc, and and the rest of the package flotsam/jetsam that can be done too.  If I understand you correctly.

**Comment by dvzrv** [comment]
Yes, setup.{py,cfg} would be very good, as this way you can install it on a distribution level and are not stuck on using pypi.

Having this package in better "versioning shape" would have the benefit of offering a non-git package in Arch Linux AUR.

Btw. I'm planning on using it here: http://sonicbikes.net/
Will be a great companion to other sensor related scripts that we're planning to include!

**Comment by wadda** [comment]
Is this more what you were thinking? 

Good idea on the bike, by the way.  I wanted and offline map reader with gps track on my bike a couple of years ago, but was distracted by other shiny things.
