### ISSUE TITLE
Version number needs incrementing

### ISSUE THREAD

**Issue by martyn-w** [wadda/gps3#9]
Hi @wadda,

I'm just experimenting with gps3 but I've noticed that the bug on line 162 of gps3.py (`key in packages['DEVICE']` as opposed to `key in self.packages['DEVICE']`) still persists if I install gps3 via `pip install gps3`. I suspect this is because the version number (0.32.0) has not been incremented with the bug fix. Would you mind updating the version number?

Thanks and good work by the way!

Martyn.

**Comment by wadda** [comment]
Sorry about that.  I'm making some changes to reduce confusion in the namespace and the package and unifying the two varieties of clients (dictionary/attributes).

My only excuse would be to say the cat stepped on the keyboard...except I don't have a cat.
